{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Network Transmitted Data UE (bytes)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"ueransim\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received Data UE (bytes)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerstats_network_received_bytes{name=\"ueransim\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "dockerstats_cpu_usage_ratio{name!=\"grafana\", name!=\"confident_pike\", name!=\"prometheus\", name!=\"mongodb\", name!=\"webui\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_bytes{name!=\"prometheus\", name!=\"confident_pike\", name!=\"grafana\", name!=\"confident_pike\", name!=\"webui\", name!=\"mongodb\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}